### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by mel-d** [mel-d/web-app__swimming-competition#1]
- [x] move _added files to add folder; update controller actions
- [x] create views for each entry form
- [x] controller actions for addition forms
- [x] add links to addition forms on "view all" pages
- [x] results by event page: add view all events link
- [x] top three finishers by event page: add view all finishers; view all events link
- [x] add view competitors in this event link to view event page
- [x] find place for competitors_by_event_result
- [x] update views folders to match controllers
- [x] update views verbiage to sound more natural
- [x] add style to events page
  <br>
  <br>
